# Generated by Django 3.2.9 on 2021-11-16 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id_not', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('publicado', models.BooleanField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
