# Generated by Django 3.2.9 on 2021-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
