apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.application.name }}
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.application.port }}
  selector:
    app: {{ .Values.application.name}}
