apiVersion: v1
kind: Secret
metadata:
  name: my-deploy-secret
  namespace: argocd
type: Opaque
data:
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNCcnM3bFdpQnFnTXYzeWlGcUtTcUZSaFBIRlVyVTZHSXBKTVJ2MTk0K2cwUUFBQUpDUFFIbS9qMEI1CnZ3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQnJzN2xXaUJxZ012M3lpRnFLU3FGUmhQSEZVclU2R0lwSk1SdjE5NCtnMFEKQUFBRURyS01YSUFtYmw5QWxkeW04aEFtNFE1L3oyLzNIaFlrV1NtZmFVMGNjVUFXdXp1VmFJR3FBeS9mS0lXb3BLb1ZHRQo4Y1ZTdFRvWWlra3hHL1gzajZEUkFBQUFCbUZ5WjI5alpBRUNBd1FGQmdjPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K